### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by risatino** [risatino/seadogs-2#1]
#### Story
This project must follow the Specific Requirements from the PowerPoint presentation.

---
#### What does DONE look like?
We should cover the MVP (minimum viable product) + if there is time, bonus features

---
#### Tasks
- [x] Discuss and stay on track with primary question + secondary questions
- [x] Your visualization must include a Python Flask powered RESTful API, HTML/CSS, JavaScript, and at least one database (MySQL, MongoDB, SQLite, etc.)
- [x] Your project should include at least one JS library that we did not cover
- [x] Your project must be powered by a dataset with at least 100 records
- [x] Your project must include some level of user-driven interaction (e.g. menus, dropdowns, textboxes, etc.)
- [x] Your final visualization should ideally include at least **three views**
- [x] Your project should fall into one of the below four tracks:  
* A custom "creative" D3.js project (i.e. non-standard graph or chart) 
* A combination of Web Scraping and Leaflet or Plotly
* A dashboard page with multiple charts all updating from the same data 
* A "thick" server that performs multiple manipulations on data in a database prior to visualization (must be approved)

**Comment by risatino** [comment]
we finished this, great job everyone!
