### ISSUE TITLE
Automap CSV Data To A Database For Flask App

### ISSUE THREAD

**Issue by risatino** [risatino/seadogs-2#3]
#### Story
Hold data in a database for full stack Flask app

---
#### What does DONE look like?
Sqlite successfully holds cleaned data from CSV

---
#### Tasks
- [x] Sort/Filter Excel Workbook Data
- [x] Get help from Travis
- [x] Figure out which database works best with sqlalchemy
- [x] Take sorted csv data into (sqlite) using sqlalchemy

**Comment by nataliekramer** [comment]
flask routes still need to be written to have the sqlite tables populate as api endpoints

**Comment by risatino** [comment]
I'll open a new card for the flask routes, thanks!
