### ISSUE TITLE
Flask App Tasks

### ISSUE THREAD

**Issue by risatino** [risatino/seadogs-2#8]
#### Story
Get full stack Flask App running

---
#### What does DONE look like?
All tasks tested and complete!

---
#### Tasks (NK + RP)
- [x] Set up Flask routes + API routes 
- [x] Get API Endpoints working so sqlite table can populate
- [x] Research/Discovery in casting the tables as numeric, but try to avoid casting the the string columns as numeric (formatting)
- [x] Set up static, templates, and archive (miscellaneous) folders with starter files (RP)
- [x] Test local http runserver for Flask App
- [x] JSON API was coming as text carrots, fixed thanks NK!
- [x] Fix the routes to link all templates in use to Flask 
- [x] Working on PlotlyJS Cool Heat Map! - DH
- [x] Look into Tableau w/ SQL - BM (hard to hook up to sqlite data)
- [x] Test/Make the 3 key graphs
- [x] Carto Map - NK (not easy without timestamp)
- [x] Summary Points: Replace Content
- [x] Working HighChartJS - NK to pull data into ```data:``` scatter plot / maybe use the wizard tool

**Comment by risatino** [comment]
If you can think of other tasks to put on this, please do. Thanks!
