### ISSUE TITLE
Questions: Show 3 Views

### ISSUE THREAD

**Issue by risatino** [risatino/seadogs-2#9]
#### OVERVIEW: Is Urbanization In Decline?
Over 4 decades of data

__Primary Plot:__ Population Timeline of changes over a certain time
* USA Map with circles (ie. earthquakes and timeline tooltip)
* population.csv

- [x] Come up with the next two views (sub-plot) 

Potential Causes:
Is the Urban + Suburban Population Growth region specific?
Is employment a driving factor for our hypothesis?

#### Tasks
- [x] Discuss/Specify clear questions
- [x] Flask app NK + RP
- [x] CBSA - get lat-longs (53) BM + DH 
- [x] Create the overview map and use PlotlyJS + HighChartsJS (prototype)
- [x] Create the overview map and use PlotlyJS + HighChartsJS (with real data)
